version: '3.8'
services:
  orphan-management-prod:
    image: 211020/orphan-management:latest
    container_name: orphan-management-prod
    ports:
      - "7777:7777"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mh-rental.cceyhlcvjfnk.us-east-1.rds.amazonaws.com:5432/mhrental
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=5RQI9yPAExiQUy7gCaXX
    networks:
      - orphan-network
    restart: unless-stopped
    dns:
      - 103.162.20.4
      - 8.8.8.8
networks:
  orphan-network:
    driver: bridge
